If $DISPLAY is set, don't restart kdm, wdm, and xdm by default; instead, display a debconf error if they haven't been restarted.

diff --git a/libpam0g.postinst b/libpam0g.postinst
--- a/libpam0g.postinst
+++ b/libpam0g.postinst
@@ -52,10 +52,53 @@ filerc() {
     echo ""
 }
 
+installed_services() {
+    check="$@"
+
+    # Only get the ones that are installed, and configured
+    check=$(dpkg -s $check 2> /dev/null | egrep '^Package:|^Status:' | awk '{if ($1 ~ /^Package:/) { package=$2 } else if ($0 ~ /^Status: .* installed$/) { print package }}')
+
+    # some init scripts don't match the package names
+    check=$(echo $check | \
+	sed -e's/\bapache2-common\b/apache2/g' \
+	    -e's/\bat\b/atd/g' \
+	    -e's/\bdovecot-common\b/dovecot/g' \
+	    -e's/\bdante-server\b/danted/g' \
+	    -e's/\bexim4-base\b/exim4/g' \
+	    -e's/\bheartbeat-2\b/heartbeat/g' \
+	    -e's/\bhylafax-server\b/hylafax/g' \
+	    -e's/\bpartimage-server\b/partimaged/g' \
+	    -e's/\bsasl2-bin\b/saslauthd/g' \
+    )
+
+    for service in $check; do
+	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+	   idl=$(ls /etc/init.d/${service} 2> /dev/null | head -n 1)
+	   if [ -n "$idl" ] && [ -x $idl ]; then
+		services="$service $services"
+	   else
+		echo "WARNING: init script for $service not found." >&2
+	   fi
+	else
+	    if [ -f /usr/share/file-rc/rc ] || [ -f /usr/lib/file-rc/rc ] && [ -f /etc/runlevel.conf ]; then
+		idl=$(filerc $rl $service)
+	    else
+		idl=$(ls /etc/rc${rl}.d/S??${service} 2> /dev/null | head -n 1)
+	    fi
+	    if [ -n "$idl" ] && [ -x $idl ]; then
+	        services="$service $services"
+	    fi
+	fi
+    done
+    echo "$services"
+}
+
 if [ "$1" = "configure" ]
 then
     if [ ! -z "$2" ]; then
 	if dpkg --compare-versions "$2" lt 0.99.7.1-3; then
+	    db_version 2.0
+
 	    echo -n "Checking for services that may need to be restarted..."
 
 	    check="apache2-common at bayonne cherokee courier-authdaemon"
@@ -63,53 +106,21 @@ then
 	    check="$check dante-server diald dovecot-common exim exim4-base"
 	    check="$check fcron fireflier-server freeradius gdm heartbeat"
 	    check="$check heartbeat-2 hylafax-server iiimf-server inn2"
-	    check="$check kannel kdm linesrv linesrv-mysql lsh-server"
+	    check="$check kannel linesrv linesrv-mysql lsh-server"
 	    check="$check muddleftpd netatalk nuauth partimage-server"
 	    check="$check perdition pgpool popa3d postgresql-7.4"
 	    check="$check postgresql-8.1 postgresql-8.2 proftpd pure-ftpd"
 	    check="$check pure-ftpd-ldap pure-ftpd-mysql"
 	    check="$check pure-ftpd-postgresql racoon samba sasl2-bin"
 	    check="$check sfs-server solid-pop3d squid squid3 tac-plus"
-	    check="$check vsftpd wdm wu-ftpd wzdftpd xdm xrdp yardradius"
-	    check="$check yaws"
-	    # Only get the ones that are installed, and configured
-	    check=$(dpkg -s $check 2> /dev/null | egrep '^Package:|^Status:' | awk '{if ($1 ~ /^Package:/) { package=$2 } else if ($0 ~ /^Status: .* installed$/) { print package }}')
-	    # some init scripts don't match the package names
-	    check=$(echo $check | \
-		sed -e's/\bapache2-common\b/apache2/g' \
-		    -e's/\bat\b/atd/g' \
-		    -e's/\bdovecot-common\b/dovecot/g' \
-		    -e's/\bdante-server\b/danted/g' \
-		    -e's/\bexim4-base\b/exim4/g' \
-		    -e's/\bheartbeat-2\b/heartbeat/g' \
-		    -e's/\bhylafax-server\b/hylafax/g' \
-		    -e's/\bpartimage-server\b/partimaged/g' \
-		    -e's/\bsasl2-bin\b/saslauthd/g' \
-	    )
+	    check="$check vsftpd wu-ftpd wzdftpd xrdp yardradius yaws"
+	    if [ -z "$DISPLAY" ]; then
+		check="$check kdm wdm xdm"
+	    fi
 
 	    echo "Checking init scripts..."
-	    for service in $check; do
-		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-		   idl=$(ls /etc/init.d/${service} 2> /dev/null | head -n 1)
-		   if [ -n "$idl" ] && [ -x $idl ]; then
-			services="$service $services"
-		   else
-			echo "WARNING: init script for $service not found."
-		   fi
-		else
-		    if [ -f /usr/share/file-rc/rc ] || [ -f /usr/lib/file-rc/rc ] && [ -f /etc/runlevel.conf ]; then
-			idl=$(filerc $rl $service)
-		    else
-			idl=$(ls /etc/rc${rl}.d/S??${service} 2> /dev/null | head -n 1)
-		    fi
-		    if [ -n "$idl" ] && [ -x $idl ]; then
-		        services="$service $services"
-		    fi
-		fi
-	    done
+	    services=$(installed_services "$check")
 	    if [ -n "$services" ]; then
-		db_version 2.0
-
 		db_reset libpam0g/restart-services
 		db_set libpam0g/restart-services "$services"
 		db_input critical libpam0g/restart-services || true
@@ -161,7 +172,6 @@ then
 		    done
 		    echo
 		    if [ -n "$failed" ]; then
-			db_fset libpam0g/restart-failed seen false
 			db_subst libpam0g/restart-failed services "$failed"
 			db_input critical libpam0g/restart-failed || true
 			db_go || true
@@ -170,12 +180,28 @@ then
 		    fi
 		    echo
 		fi
-		# Shut down the frontend, to make sure none of the
-		# restarted services keep a connection open to it
-		db_stop
 	    else
 		echo "Nothing to restart."
 	    fi
+
+	    if [ -n "$DISPLAY" ]; then
+		dms=""
+		for service in kdm wdm xdm; do
+		    case "$services" in
+			*$service*)	;;
+			*)	dms="$dms $service"
+		    esac
+		done
+		services=$(installed_services "$dms")
+		if [ -n "$services" ]; then
+		    db_input critical libpam0g/xdm-needs-restart || true
+		    db_go || true
+		fi
+	    fi
+
+	    # Shut down the frontend, to make sure none of the
+	    # restarted services keep a connection open to it
+	    db_stop
 	fi # end upgrading and $2 lt 0.99.7.1-3
     fi # Upgrading
 fi
