Clean up the libpam0g postinst a bit; invoke-rc.d has been a guaranteed interface for two stable release cycles now

diff --git a/debian/libpam0g.postinst b/debian/libpam0g.postinst
--- a/debian/libpam0g.postinst
+++ b/debian/libpam0g.postinst
@@ -72,22 +72,11 @@ installed_services() {
     )
 
     for service in $check; do
-	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-	   idl=$(ls /etc/init.d/${service} 2> /dev/null | head -n 1)
-	   if [ -n "$idl" ] && [ -x $idl ]; then
+	idl="/etc/init.d/${service}"
+	if [ -n "$idl" ] && [ -x $idl ]; then
 		services="$service $services"
-	   else
-		echo "WARNING: init script for $service not found." >&2
-	   fi
 	else
-	    if [ -f /usr/share/file-rc/rc ] || [ -f /usr/lib/file-rc/rc ] && [ -f /etc/runlevel.conf ]; then
-		idl=$(filerc $rl $service)
-	    else
-		idl=$(ls /etc/rc${rl}.d/S??${service} 2> /dev/null | head -n 1)
-	    fi
-	    if [ -n "$idl" ] && [ -x $idl ]; then
-	        services="$service $services"
-	    fi
+		echo "WARNING: init script for $service not found." >&2
 	fi
     done
     echo "$services"
@@ -140,13 +129,7 @@ then
 		    failed=""
 		    rl=$(runlevel | sed 's/.*\ //')
 		    for service in $services; do
-			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-			    idl="invoke-rc.d ${service}"
-			elif [ -f /usr/share/file-rc/rc ] || [ -f /usr/lib/file-rc/rc ] && [ -f /etc/runlevel.conf ]; then
-			    idl=$(filerc $rl $service)
-			else
-			    idl=$(ls /etc/rc${rl}.d/S??${service} 2> /dev/null | head -n 1)
-			fi
+			idl="invoke-rc.d ${service}"
 
 			case "$service" in
 			    gdm)
